export const EMPLOYEES = [{
        matricula: "1234",
        nome: "Cary",
        email: "cmorland0@wsj.com",
        setor: "TI",
        dataNascimento: "3/25/2021",
        ramal: "812",
    },
    {
        matricula: "1235",
        nome: "Monah",
        email: "mgorke1@vkontakte.ru",
        setor: "Product Management",
        dataNascimento: "3/11/2021",
        ramal: "818",
    },
    {
        matricula: "1236,
        nome: "Erda",
        email: "efletham2@desdev.cn",
        setor: "Legal",
        dataNascimento: "12/4/2021",
        ramal: "825",
    },
    {
        matricula: "1237",
        nome: "Ediva",
        email: "elarway3@ocn.ne.jp",
        setor: "Product Management",
        dataNascimento: "1/24/2021",
        ramal: "526",
    },
    {
        matricula: "1239",
        nome: "Cacilia",
        email: "cmant4@barnesandnoble.com",
        setor: "Marketing",
        dataNascimento: "9/15/2021",
        ramal: "625",
    },
    {
        matricula: "1230",
        nome: "Marylin",
        email: "mstainburn5@blinklist.com",
        setor: "Marketing",
        dataNascimento: "7/26/2021",
        ramal: "789",
    },
    {
        matricula: "1231",
        nome: "Shane",
        email: "sovill6@canalblog.com",
        setor: "Support",
        dataNascimento: "2/9/2021",
        ramal: "658",
    },
];